-- CreateTable
CREATE TABLE "TB_USUARIO" (
    "UsuId" SERIAL NOT NULL,
    "UsuNom" VARCHAR(100) NOT NULL,
    "UsuEma" VARCHAR(100) NOT NULL,
    "UsuCon" VARCHAR(255) NOT NULL,
    "UsuTip" VARCHAR(20) NOT NULL,
    "UsuFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UsuFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UsuAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_USUARIO_pkey" PRIMARY KEY ("UsuId")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_USUARIO_UsuEma_key" ON "TB_USUARIO"("UsuEma");
