-- CreateTable
CREATE TABLE "TB_CATEGORIA" (
    "CatId" SERIAL NOT NULL,
    "CatNom" VARCHAR(100) NOT NULL,
    "CatDes" TEXT,
    "CatFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CatFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CatAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_CATEGORIA_pkey" PRIMARY KEY ("CatId")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_CATEGORIA_CatNom_key" ON "TB_CATEGORIA"("CatNom");
