-- AlterTable
ALTER TABLE "TB_MATERIAL_FISICO" ADD COLUMN     "MatFisAct" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE "TB_MATERIAL_VIRTUAL" ADD COLUMN     "MatVirAct" BOOLEAN NOT NULL DEFAULT true;
