-- AlterTable
ALTER TABLE "TB_MATERIAL_FISICO" ADD COLUMN     "MatFisFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "MatFisFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TB_MATERIAL_VIRTUAL" ADD COLUMN     "MatVirFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "MatVirFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
