-- CreateEnum
CREATE TYPE "TipoPrestamo" AS ENUM ('FISICO', 'VIRTUAL');

-- CreateEnum
CREATE TYPE "FormatoMaterial" AS ENUM ('FISICO', 'VIRTUAL', 'MIXTO');

-- CreateTable
CREATE TABLE "TB_MATERIAL_BIBLIOGRAFICO" (
    "MatBibId" SERIAL NOT NULL,
    "MatBibCod" VARCHAR(50) NOT NULL,
    "MatBibTit" VARCHAR(200) NOT NULL,
    "MatBibAut" VARCHAR(200) NOT NULL,
    "CatId" INTEGER NOT NULL,
    "MatBibFor" "FormatoMaterial" NOT NULL,
    "MatBibFecPub" DATE,
    "MatBibFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MatBibFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "MatBibAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_MATERIAL_BIBLIOGRAFICO_pkey" PRIMARY KEY ("MatBibId")
);

-- CreateTable
CREATE TABLE "TB_MATERIAL_FISICO" (
    "MatFisId" SERIAL NOT NULL,
    "MatBibId" INTEGER NOT NULL,
    "MatFisCodEje" VARCHAR(50) NOT NULL,
    "MatFisEst" VARCHAR(20) NOT NULL,
    "MatFisUbi" VARCHAR(100) NOT NULL,

    CONSTRAINT "TB_MATERIAL_FISICO_pkey" PRIMARY KEY ("MatFisId")
);

-- CreateTable
CREATE TABLE "TB_MATERIAL_VIRTUAL" (
    "MatVirId" SERIAL NOT NULL,
    "MatBibId" INTEGER NOT NULL,
    "MatVirUrlAcc" VARCHAR(255) NOT NULL,
    "MatVirForArc" VARCHAR(50) NOT NULL,

    CONSTRAINT "TB_MATERIAL_VIRTUAL_pkey" PRIMARY KEY ("MatVirId")
);

-- CreateTable
CREATE TABLE "TB_AUTOR" (
    "AutId" SERIAL NOT NULL,
    "AutNom" VARCHAR(100) NOT NULL,
    "AutApe" VARCHAR(100) NOT NULL,
    "AutEma" VARCHAR(100),
    "AutFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AutFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AutAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_AUTOR_pkey" PRIMARY KEY ("AutId")
);

-- CreateTable
CREATE TABLE "TB_AUTOR_MATERIAL" (
    "AutMatId" SERIAL NOT NULL,
    "MatBibId" INTEGER NOT NULL,
    "AutId" INTEGER NOT NULL,
    "AutMatFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "AutMatAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_AUTOR_MATERIAL_pkey" PRIMARY KEY ("AutMatId")
);

-- CreateTable
CREATE TABLE "TB_PRESTAMO" (
    "PreId" SERIAL NOT NULL,
    "LecId" INTEGER NOT NULL,
    "UsuId" INTEGER NOT NULL,
    "PreFecPre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PreFecVen" TIMESTAMP(3),
    "PreFecDev" TIMESTAMP(3),
    "PreEst" VARCHAR(20) NOT NULL,
    "PreObs" TEXT,
    "PreFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PreFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PreAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_PRESTAMO_pkey" PRIMARY KEY ("PreId")
);

-- CreateTable
CREATE TABLE "TB_PRESTAMO_DETALLE" (
    "PreDetId" SERIAL NOT NULL,
    "PreId" INTEGER NOT NULL,
    "MatBibId" INTEGER NOT NULL,
    "MatFisId" INTEGER,
    "MatVirId" INTEGER,
    "PreTip" "TipoPrestamo" NOT NULL,
    "PreFecVen" TIMESTAMP(3),
    "PreFecDev" TIMESTAMP(3),
    "PreEst" VARCHAR(20) NOT NULL,

    CONSTRAINT "TB_PRESTAMO_DETALLE_pkey" PRIMARY KEY ("PreDetId")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_MATERIAL_BIBLIOGRAFICO_MatBibCod_key" ON "TB_MATERIAL_BIBLIOGRAFICO"("MatBibCod");

-- CreateIndex
CREATE UNIQUE INDEX "TB_MATERIAL_FISICO_MatBibId_MatFisCodEje_key" ON "TB_MATERIAL_FISICO"("MatBibId", "MatFisCodEje");

-- CreateIndex
CREATE UNIQUE INDEX "TB_MATERIAL_VIRTUAL_MatBibId_key" ON "TB_MATERIAL_VIRTUAL"("MatBibId");

-- CreateIndex
CREATE UNIQUE INDEX "TB_AUTOR_MATERIAL_MatBibId_AutId_key" ON "TB_AUTOR_MATERIAL"("MatBibId", "AutId");

-- AddForeignKey
ALTER TABLE "TB_MATERIAL_BIBLIOGRAFICO" ADD CONSTRAINT "TB_MATERIAL_BIBLIOGRAFICO_CatId_fkey" FOREIGN KEY ("CatId") REFERENCES "TB_CATEGORIA"("CatId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_MATERIAL_FISICO" ADD CONSTRAINT "TB_MATERIAL_FISICO_MatBibId_fkey" FOREIGN KEY ("MatBibId") REFERENCES "TB_MATERIAL_BIBLIOGRAFICO"("MatBibId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_MATERIAL_VIRTUAL" ADD CONSTRAINT "TB_MATERIAL_VIRTUAL_MatBibId_fkey" FOREIGN KEY ("MatBibId") REFERENCES "TB_MATERIAL_BIBLIOGRAFICO"("MatBibId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_AUTOR_MATERIAL" ADD CONSTRAINT "TB_AUTOR_MATERIAL_MatBibId_fkey" FOREIGN KEY ("MatBibId") REFERENCES "TB_MATERIAL_BIBLIOGRAFICO"("MatBibId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_AUTOR_MATERIAL" ADD CONSTRAINT "TB_AUTOR_MATERIAL_AutId_fkey" FOREIGN KEY ("AutId") REFERENCES "TB_AUTOR"("AutId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO" ADD CONSTRAINT "TB_PRESTAMO_LecId_fkey" FOREIGN KEY ("LecId") REFERENCES "TB_LECTOR"("LecId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO" ADD CONSTRAINT "TB_PRESTAMO_UsuId_fkey" FOREIGN KEY ("UsuId") REFERENCES "TB_USUARIO"("UsuId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO_DETALLE" ADD CONSTRAINT "TB_PRESTAMO_DETALLE_PreId_fkey" FOREIGN KEY ("PreId") REFERENCES "TB_PRESTAMO"("PreId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO_DETALLE" ADD CONSTRAINT "TB_PRESTAMO_DETALLE_MatBibId_fkey" FOREIGN KEY ("MatBibId") REFERENCES "TB_MATERIAL_BIBLIOGRAFICO"("MatBibId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO_DETALLE" ADD CONSTRAINT "TB_PRESTAMO_DETALLE_MatFisId_fkey" FOREIGN KEY ("MatFisId") REFERENCES "TB_MATERIAL_FISICO"("MatFisId") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRESTAMO_DETALLE" ADD CONSTRAINT "TB_PRESTAMO_DETALLE_MatVirId_fkey" FOREIGN KEY ("MatVirId") REFERENCES "TB_MATERIAL_VIRTUAL"("MatVirId") ON DELETE SET NULL ON UPDATE CASCADE;
