-- CreateTable
CREATE TABLE "TB_LECTOR" (
    "LecId" SERIAL NOT NULL,
    "LecDni" VARCHAR(8) NOT NULL,
    "LecNom" VARCHAR(100) NOT NULL,
    "LecApe" VARCHAR(100) NOT NULL,
    "LecTip" VARCHAR(20) NOT NULL,
    "LecEma" VARCHAR(100),
    "LecFecCre" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LecFecAct" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LecAct" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "TB_LECTOR_pkey" PRIMARY KEY ("LecId")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_LECTOR_LecDni_key" ON "TB_LECTOR"("LecDni");
